const { days } = require("./daysHelper");
const viewSalaryResponse = (rows) => {
  let response = [];
  rows.forEach((item) => {
    let obj = {};
    obj.t_id = item.t_id;
    obj.s_id = item.s_id;
    obj.d_id = item.d_id;
    obj.dep_id = item.dep_id;
    obj.department = item.department;
    obj.name = item.name;
    obj.designation = item.designation;
    obj.epf_no = item.epf_no;
    obj.monthly_s = item.monthly_s;
    obj.lwp = item.lwp;
    obj.present = days(item.month, item.year) - item.lwp;
    obj.gross_s = item.gross_s;
    obj.pm_over_time = item.pm_over_time;
    obj.epf_share = item.epf_share;
    obj.pm_less_payment = item.pm_less_payment;
    obj.adv_payment = item.adv_payment;
    obj.total_payment = item.total_payment;
    obj.cheque_no_date = item.cheque_no_date;
    obj.total_deposit = item.total_deposit;
    obj.daysOfMonth = days(item.month, item.year);
    obj.is_epf_applied = item.is_epf_applied;
    obj.epf_contribution = item.epf_contribution;
    obj.eps_contribution = item.eps_contribution;
    obj.diff_epf_eps = item.diff_epf_eps;
    obj.ncp_days = item.ncp_days;
    obj.refund_advn = item.refund_advn;
    response.push(obj);
  });
  return response;
};
const viewAddResponse = (rows) => {
  let response = [];
  rows.forEach((item) => {
    let obj = {};
    obj.t_id = item.t_id;
    obj.s_id = item.s_id;
    obj.d_id = item.d_id;
    obj.dep_id = item.dep_id;
    obj.department = item.department;
    obj.name = item.name;
    obj.designation = item.designation;
    obj.epf_no = item.epf_no;
    obj.monthly_s = item.monthly_s;
    obj.lwp = item.lwp;
    obj.present = days(item.month, item.year) - item.lwp;
    obj.gross_s = item.gross_s;
    obj.pm_over_time = item.pm_over_time;
    obj.epf_share = item.epf_share;
    obj.pm_less_payment = item.pm_less_payment;
    obj.adv_payment = item.adv_payment;
    obj.total_payment = item.total_payment;
    obj.cheque_no_date = item.cheque_no_date;
    obj.total_deposit = item.total_deposit;
    obj.daysOfMonth = days(item.month, item.year);
    obj.is_epf_applied = item.is_epf_applied;
    obj.epf_contribution = item.epf_contribution;
    obj.eps_contribution = item.eps_contribution;
    obj.diff_epf_eps = item.diff_epf_eps;
    obj.ncp_days = item.ncp_days;
    obj.refund_advn = item.refund_advn;
    obj.gender = item.gender;
    obj.dob = item.dob;
    obj.address = item.address;
    obj.email = item.email;
    obj.phone = item.phone;
    obj.ac_no = item.ac_no;
    obj.uan = item.uan;
    obj.category = item.category;
    obj.aadhaar_no = item.aadhaar_no;
    obj.pan_no = item.pan_no;
    obj.b_name = item.b_name;
    obj.prof_qualification = item.prof_qualification;
    obj.qualification = item.qualification;
    response.push(obj);
  });
  return response;
};

module.exports = { viewSalaryResponse, viewAddResponse };
